// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ongxvnqczcuokkrokbrd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9uZ3h2bnFjemN1b2trcm9rYnJkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMyNjAzNjEsImV4cCI6MjA2ODgzNjM2MX0.sI1f-CbaO2aN0Nv8XHxrkssuMhmDIc7tLfyVnL7pAxw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});